-- Bronze Layer: Raw FMP API Data
CREATE OR REPLACE DATABASE FMP_DB;
CREATE OR REPLACE SCHEMA BRONZE;

USE DATABASE FMP_DB;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE FMP_PROFILES (
    SYMBOL STRING,
    COMPANY_NAME STRING,
    INDUSTRY STRING,
    SECTOR STRING,
    COUNTRY STRING,
    CEO STRING,
    WEBSITE STRING,
    DESCRIPTION STRING,
    MARKET_CAP FLOAT,
    REVENUE FLOAT,
    EBIT FLOAT,
    INCOME FLOAT,
    PROFIT_MARGIN FLOAT,
    RAW_DATA VARIANT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE STAGE S3_BRONZE_STAGE
    URL = 's3://fmp-raw-data-uzan/bronze/'
    STORAGE_INTEGRATION = s3_int
    FILE_FORMAT = (TYPE = JSON);
