-- Gold Layer: Aggregated Business Insights
CREATE OR REPLACE SCHEMA GOLD;

USE DATABASE FMP_DB;
USE SCHEMA GOLD;

-- 1. Sector-wise summary
CREATE OR REPLACE TABLE SECTOR_SUMMARY (
    SECTOR STRING PRIMARY KEY,
    TOTAL_COMPANIES INT,
    AVG_MARKET_CAP_B FLOAT,
    AVG_PROFIT_MARGIN FLOAT,
    TOTAL_REVENUE_B FLOAT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Top 10 companies by market cap
CREATE OR REPLACE TABLE TOP_COMPANIES (
    SYMBOL STRING PRIMARY KEY,
    COMPANY_NAME STRING,
    SECTOR STRING,
    MARKET_CAP_B FLOAT,
    PROFIT_MARGIN FLOAT,
    RANK INT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
