-- Silver Layer: Cleaned Company Profiles
CREATE OR REPLACE SCHEMA SILVER;

USE DATABASE FMP_DB;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE COMPANY_PROFILES (
    SYMBOL STRING PRIMARY KEY,
    COMPANY_NAME STRING,
    INDUSTRY STRING,
    SECTOR STRING,
    COUNTRY STRING,
    CEO STRING,
    WEBSITE STRING,
    DESCRIPTION STRING,
    MARKET_CAP_B FLOAT,
    REVENUE_B FLOAT,
    EBIT_M FLOAT,
    NET_INCOME_M FLOAT,
    PROFIT_MARGIN FLOAT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
